import { Investment } from '@/types/data';

export const investments: Investment[] = [
  {
    id: 1,
    name: 'Niepołomice strefa',
    address: {
      city: 'Niepołomice',
      street: 'Portowa',
      number: '13',
    },
    investor: {
      name: 'ATAL',
      contactPerson: 'Zbigniew Jaroszek',
      email: 'zjaroszek@atal.pl',
      phone: '502304402',
      address: {
        city: 'Kraków',
        street: 'Krowoderska',
        number: '67a',
      },
      nip: '5124927582',
      regon: '57283295871824',
    },
    issueDate: '2023-10-12',
    inspectionDate: '2024-03-14',
    inspectionDone: false,
    decisionDate: '2024-05-06',
    deforestationDate: '2024-10-12',
    deforestationDone: false,
    plantingDate: '2024-09-28',
    plantingDone: false,
    applicationData: {
      signature: 'SKN/12/2024',
      isCommercial: false,
      deforestationCause: 'Choroba drzew',
      deforestationDate: '2024-06-27',
      plantingDate: '2024-09-12',
      plantingSite: 'Nowa Huta, Nabielaka 12c',
      species: 'Klon czerwony, Lipa zwyczajna',
    },
    notes: [
      {
        date: '2024-02-12',
        content: 'Kod do brammy: #411232',
      },
      {
        date: '2024-03-14',
        content: 'Telefon do ochrony: 412 213 213',
      },
    ],
  },
  {
    id: 2,
    name: 'Tarnów centrum',
    address: {
      city: 'Tarnów',
      street: 'Słoneczna',
      number: '24',
    },
    investor: {
      name: 'Tarnów Mościce',
      contactPerson: 'Magdalena Pietras',
      email: 'mpietras@igt.pl',
      phone: '495 102 203',
      address: {
        city: 'Tarnów',
        street: 'Długa',
        number: '80',
      },
      nip: '5030020012',
      regon: '57345918271921',
    },
    issueDate: '2023-08-15',
    inspectionDate: '2024-04-19',
    inspectionDone: true,
    decisionDate: '2024-05-22',
    deforestationDate: '2023-11-09',
    deforestationDone: true,
    plantingDate: '2024-04-25',
    plantingDone: true,
    applicationData: {
      signature: 'SVG/24/2023',
      isCommercial: true,
      deforestationCause: 'Rozbudowa kompleksu biurowego',
      deforestationDate: '2023-11-09',
      plantingDate: '2024-04-25',
      plantingSite: 'Brzesko, Ogrodowa 4',
      species: 'Dąb szypułkowy, Buk pospolity',
    },
    notes: [
      {
        date: '2023-09-23',
        content: 'Zmiana planu zagospodarowania',
      },
      {
        date: '2023-10-31',
        content: 'Uwaga na nowe przepisy dot. izolacji',
      },
    ],
  },
  {
    id: 3,
    name: 'Kraków Zakamycze',
    address: {
      city: 'Kraków',
      street: 'Widok',
      number: '29',
    },
    investor: {
      name: 'Urban Development Sp. z o.o.',
      contactPerson: 'Anna Kowalczyk',
      email: 'akowalczyk@urbandev.pl',
      phone: '508 300 345',
      address: {
        city: 'Kraków',
        street: 'Kazimierza Wielkiego',
        number: '56',
      },
      nip: '6750001029',
      regon: '36529876500000',
    },
    issueDate: '2023-09-01',
    inspectionDate: '2024-01-15',
    inspectionDone: true,
    decisionDate: '2024-02-10',
    deforestationDate: '2023-12-01',
    deforestationDone: true,
    plantingDate: '2024-08-30',
    plantingDone: false,
    applicationData: {
      signature: 'KDW/15/2023',
      isCommercial: true,
      deforestationCause: 'Modernizacja centrum biznesowego',
      deforestationDate: '2023-12-01',
      plantingDate: '2024-03-30',
      plantingSite: 'Bieżanów-Prokocim, Osiedle Młodych',
      species: 'Jesion wyniosły, Brzoza brodawkowata',
    },
    notes: [
      {
        date: '2023-10-02',
        content: 'Spotkanie w sprawie dostaw materiałów',
      },
      {
        date: '2023-11-25',
        content: 'Pilne: konsultacje z urbanistą',
      },
    ],
  },
  {
    id: 4,
    name: 'Bielsko-Biała',
    address: {
      city: 'Bielsko-Biała',
      street: 'Handlowa',
      number: '5',
    },
    investor: {
      name: 'BBRetail Co.',
      contactPerson: 'Jacek Szymański',
      email: 'jszymanski@bbretail.pl',
      phone: '503 204 205',
      address: {
        city: 'Bielsko-Biała',
        street: 'Fabryczna',
        number: '88',
      },
      nip: '8020003044',
      regon: '650320928',
    },
    issueDate: '2023-11-16',
    inspectionDate: '2024-06-10',
    inspectionDone: true,
    decisionDate: '2024-07-25',
    deforestationDate: '2024-05-20',
    deforestationDone: true,
    plantingDate: '2024-11-15',
    plantingDone: false,
    applicationData: {
      signature: 'BBR/06/2024',
      isCommercial: true,
      deforestationCause: 'Budowa nowego centrum handlowego',
      deforestationDate: '2024-05-20',
      plantingDate: '2024-08-15',
      plantingSite: 'Wapienica, Ulica Leśna',
      species: 'Sosna zwyczajna, Świerk pospolity',
    },
    notes: [
      {
        date: '2023-12-03',
        content: 'Zmiana wykonawcy robót ziemnych',
      },
      {
        date: '2024-01-14',
        content: 'Załatwić dodatkowe zezwolenia na użytkowanie drogi',
      },
    ],
  },
];
